apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
  namespace: myapp
type: Opaque
stringData:
  DB_HOST: mybank-db.cxewkiaq63tk.ap-southeast-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: mybank
  DB_USER: admin
  DB_PASSWORD: alemvmfhwprxm2